### ISSUE TITLE
postcss@8.2.6: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by SotaWatanabe** [PlasmNetwork/plasm-apps-vue#20]
<img width="567" alt="Screen Shot 2021-03-24 at 22 56 15" src="https://user-images.githubusercontent.com/29359048/112327462-caf89980-8cf8-11eb-886c-e56b066d8bc4.png">

How can i resolve this error?

error postcss@8.2.6: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || >=14". Got "13.7.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

I checked the package.json and fond "postcss". my version was 8.2.6.

**Comment by hoonsubin** [comment]
The poscss module expects node.js 14. Please install the latest version of node on your system
